apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: nodeapp
  name: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nodeapp-exposed
  template:
    metadata:
      labels:
        run: nodeapp-exposed
    spec:
      containers:
      - image: veermaste03/myrepo1:v1.0
        name: nodeapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
          protocol: TCP
        # env:
        # - name: ENV
        #   value: "production"
        # - name: SECRET_USERNAME
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-user-pass
        #       key: username
        # - name: SECRET_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: db-user-pass
        #       key: password
        
