apiVersion: v1
kind: Service
metadata:
  labels:
    run: nodeapp
  name: nodeapp
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8090
  selector:
    run: nodeapp-exposed
  type: NodePort
